### ISSUE TITLE
StalkerBot is not loading

### ISSUE THREAD

**Issue by jmandrade** [gbin/err-stalkerbot#2]
Don't really know what the issue is. !status reports StalkerBot with an E=Error. Here's what I believe is the pertinent info from the log:

2013-10-19 20:08:39,823 INFO received command = repos_install matching [repos_install] with parameters [err-stalkerbot]
2013-10-19 20:08:43,711 INFO webhooks:  Bind /echo/ to echo
2013-10-19 20:08:43,754 ERROR Unable to import plugin: /home/pi/err/plugins/err-stalkerbot/stalkerBot
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yapsy/PluginManager.py", line 487, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/pi/err/plugins/err-stalkerbot/stalkerBot.py", line 1, in <module>
    from errbot.utils import get_jid_from_message,format_timedelta
ImportError: cannot import name get_jid_from_message

**Comment by gbin** [comment]
fixed
