### ISSUE TITLE
Unable to install+load, Python3.4, ValueError("Missing *name* of the plugin in extracted infos.")

### ISSUE THREAD

**Issue by brycied00d** [gbin/err-stalkerbot#5]
Maybe caused by case sensitivity ("stalkerBot.py" vs "class StalkerBot" vs "stalkerbot.plug")? Just a guess since I'm not familiar with Yapsy.

Debug log:

```
18:54:17 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <message to="errbot@sanitized/b79bfc81-91fa-4f5f-b7ee-00fe34ffc115" from="sanitized@sanitized/Cake" type="chat" id="purplec7d7468"><body>@repos install https://github.com/gbin/err-stalkerbot.git</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><p>@repos install <a href="https://github.com/gbin/err-stalkerbot.git">https://github.com/gbin/err-stalkerbot.git</a></p></body></html></message>
18:54:17 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: message
18:54:17 DEBUG    root                      *** jid = sanitized@sanitized/Cake
18:54:17 DEBUG    root                      *** username = sanitized
18:54:17 DEBUG    root                      *** type = chat
18:54:17 DEBUG    root                      *** text = @repos install https://github.com/gbin/err-stalkerbot.git
18:54:17 INFO     root                      Processing command 'repos_install' with parameters 'https://github.com/gbin/err-stalkerbot.git' from sanitized@sanitized/Cake/
18:54:17 DEBUG    root                      check dependencies of /usr/local/lib/python3.4/dist-packages/errbot/builtins
18:54:17 DEBUG    root                      /usr/local/lib/python3.4/dist-packages/errbot/builtins has no requirements.txt file
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-imagebot
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-stalkerbot
18:54:17 DEBUG    root                      /path/to/errbot/plugins/err-stalkerbot has no requirements.txt file
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-dictbot
18:54:17 DEBUG    root                      /path/to/errbot/plugins/err-dictbot has no requirements.txt file
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-stalkerbot
18:54:17 DEBUG    root                      /path/to/errbot/plugins/err-stalkerbot has no requirements.txt file
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-dictbot
18:54:17 DEBUG    root                      /path/to/errbot/plugins/err-dictbot has no requirements.txt file
18:54:17 DEBUG    root                      check dependencies of /path/to/errbot/plugins/err-imagebot
18:54:17 ERROR    root                      An error happened while processing a message ("@repos install https://github.com/gbin/err-stalkerbot.git") from sanitized@sanitized/Cake: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/base.py", line 994, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 542, in repos_install
    errors = self.update_dynamic_plugins()
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 175, in update_dynamic_plugins
    self.bot_config.BOT_EXTRA_PLUGIN_DIR, self.bot_config.AUTOINSTALL_DEPS)
  File "/usr/local/lib/python3.4/dist-packages/errbot/plugin_manager.py", line 227, in update_plugin_places
    simplePluginManager.locatePlugins()
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginManager.py", line 442, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 432, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 386, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 266, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.
"
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/base.py", line 994, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 542, in repos_install
    errors = self.update_dynamic_plugins()
  File "/usr/local/lib/python3.4/dist-packages/errbot/errBot.py", line 175, in update_dynamic_plugins
    self.bot_config.BOT_EXTRA_PLUGIN_DIR, self.bot_config.AUTOINSTALL_DEPS)
  File "/usr/local/lib/python3.4/dist-packages/errbot/plugin_manager.py", line 227, in update_plugin_places
    simplePluginManager.locatePlugins()
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginManager.py", line 442, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 432, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 386, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginFileLocator.py", line 266, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.
18:54:17 DEBUG    root                      Determined that [Computer says nooo. See logs for details.:
 Missing *name* of the plugin in extracted infos.] is not XHTML-IM (syntax error: line 1, column 0)
18:54:17 DEBUG    root                      All plugins: Webserver, DictBot, Cartoons, ChatRoom, ImageBot, VersionChecker, BeerBot
18:54:17 DEBUG    sleekxmpp.xmlstream.xmlst SEND: <message xml:lang="en" to="sanitized@sanitized/Cake" type="chat"><body>Computer says nooo. See logs for details.:
 Missing *name* of the plugin in extracted infos.</body></message>
18:54:17 DEBUG    root                      All plugins: Webserver, DictBot, Cartoons, ChatRoom, ImageBot, VersionChecker, BeerBot
18:54:17 DEBUG    root                      callback_message for Webserver
18:54:17 DEBUG    root                      callback_message for DictBot
18:54:17 DEBUG    root                      callback_message for Cartoons
18:54:17 DEBUG    root                      callback_message for ChatRoom
18:54:17 DEBUG    root                      callback_message for ImageBot
```

Installed Python3 libraries:

```
beautifulsoup4 (4.3.2)
bottle (0.12.8)
cffi (0.8.6)
chardet (2.3.0)
colorama (0.3.2)
colorlog (2.6.0)
cryptography (0.9)
daemonize (2.3.1)
devscripts (2.15.3)
dnspython3 (1.12.0)
err (2.2.1)
html5lib (0.999)
idna (2.0)
Jinja2 (2.7.3)
lxml (3.4.0)
Magic-file-extensions (0.2)
MarkupSafe (0.23)
Paste (1.7.5.1)
PasteDeploy (1.5.2)
pip (1.5.6)
ply (3.4)
pyasn1 (0.1.7)
pycparser (2.10)
pyOpenSSL (0.15.1)
python-apt (0.9.3.11)
python-debian (0.1.27)
requests (2.4.3)
setuptools (17.0)
six (1.9.0)
sleekxmpp (1.3.1)
Tempita (0.5.2)
unattended-upgrades (0.1)
urllib3 (1.9.1)
waitress (0.8.9)
WebOb (1.4.1)
WebTest (2.0.18)
wheel (0.24.0)
Yapsy (1.11.23)
```

**Comment by brycied00d** [comment]
Hmm, uninstalling and attempting to reinstall plugins I've successfully installed already is coming up with the same error (it seems like all plugins are), so I'm not really sure what's going on but it doesn't seem to be an issue with this module specifically.

**Comment by gbin** [comment]
Thx for the feedback, this is weird, the error tells that it doesn't find the Name metadata from the plug file ?
can you check if in the [data directory]/plugins the plugins are here correctly ?

**Comment by brycied00d** [comment]
The plugins were there and in the one plugin directory I checked, all files were present.

I ended up deleting all directories (and Core.db) and was able to install plugins once again. I'm guessing that one of the plugins directories was "corrupt" and that fouled up the whole load process. (I couldn't even restart err, it would die with that error while loading)

Closing this for now. Will update if I come across it again.

**Comment by brycied00d** [comment]
Hm, something about this one single plugin. I have a handful of other plugins installed and working fine. As soon as I install err-stalkerbot, the above issue crops up. git confirms that the files in err-stalkerbot/ are up to date.
Edit: Added repos export:

```
{'err-dnsnative': 'https://github.com/daenney/err-dnsnative.git', 'err-imagebot': 'https://github.com/gbin/err-imagebot.git', 'err-time': 'https://github.com/gbin/err-time.git', 'err-linksBot': 'https://github.com/vaz-ar/err-linksBot.git', 'err-stalkerbot': 'https://github.com/gbin/err-stalkerbot.git'}
```

**Comment by gbin** [comment]
Just reproduced it on the bot of https://gitter.im/gbin/err
!repos install err-stalkerbot
01010010 a few seconds ago  
Computer says nooo. See logs for details.:
Missing name of the plugin in extracted infos.

**Comment by gbin** [comment]
doh, there are 2 python sections in the file ... fixing it.

**Comment by gbin** [comment]
Thx a lot for tracking that down !

**Comment by brycied00d** [comment]
Excellent! And I didn't do any tracking down, that was all you. It's so obvious, I should've seen it myself.
